spring: 
  profiles:
  active:
  - dev
---
spring: 
  profiles: dev #开发环境
  application: 
    name: microservicecloud-config-mil-dev
---
spring: 
  profiles: test #测试环境
  application: 
    name: microservicecloud-config-mil-test

#保存为utf-8 保存为utf-8 保存为utf-8